admissionController: { replicas: 1 }
backgroundController: { replicas: 1 }
cleanupController: { replicas: 1 }
reportsController: { replicas: 1 }

cleanupJobs:
  admissionReports:
    image:
      repository: bitnamilegacy/kubectl
      tag: "1.28.5"
      pullPolicy: IfNotPresent
  clusterAdmissionReports:
    image:
      repository: bitnamilegacy/kubectl
      tag: "1.28.5"
      pullPolicy: IfNotPresent
  ephemeralReports:
    image:
      repository: bitnamilegacy/kubectl
      tag: "1.28.5"
      pullPolicy: IfNotPresent
  clusterEphemeralReports:
    image:
      repository: bitnamilegacy/kubectl
      tag: "1.28.5"
      pullPolicy: IfNotPresent

policyReportsCleanup:
  image:
    repository: bitnamilegacy/kubectl
    tag: "1.28.5"

webhooksCleanup:
  image:
    repository: bitnamilegacy/kubectl
    tag: "1.28.5"
