{
 "title": "Jenkins builds",
 "tags": [ "devsecops-platform" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Successful builds (total)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "default_jenkins_builds_success_build_count",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "Failed builds (total)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "default_jenkins_builds_failed_build_count",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "Last build duration (ms)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_duration_milliseconds",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  }
 ]
}